name: Build Input23DS macOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          host: 'mac'
          target: 'desktop'
          cache: true

      - name: Configure
        run: cmake -S . -B build -DCMAKE_PREFIX_PATH=$Qt6_DIR

      - name: Build
        run: cmake --build build

      - name: Find .app
        run: find build -name "*.app"

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: Input23DS-macOS
          path: build
