name: Build Input23DS macOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          host: 'mac'
          target: 'desktop'
          cache: true

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=$Qt6_DIR

      - name: Build
        run: |
          cmake --build build

      - name: Deploy app
        run: |
          $Qt6_DIR/bin/macdeployqt build/Input23DS.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Input23DS-macOS
          path: build/Input23DS.app
